name:       hmonitors
version:    0.1.0.0
license:    BSD3
author:     "Ricard Illa"
maintainer: "rilla@monotremata.xyz"
copyright:  "2020 Ricard Illa Pujagut"

extra-source-files:
- README.md

description: Please see README.md

dependencies:
- base
- containers
- process
- regex-compat
- split
- time

library:
  source-dirs: src

executables:
  hmonitors-query:
    main:        Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -Werror
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hmonitors
